### ISSUE TITLE
README.md is incomplete to get a working app

### ISSUE THREAD

**Issue by ghost** [strapi/strapi-legacy-gatsby-blog#10]
Requires addition of:

### Connect backend API and give user permissions

- Create a .env.development file in the root of `frontend` containing the following line:

`API_URL="http://localhost:1337"`

- In Strapi admin, click on the Roles & Permissions and click on the `public` role.
- Check the article and category `find` and `findone` routes and save.

**Comment by Mcastres** [comment]
Hello @chrishooper78 I fixed it inside the Strapi code, now the permissions are automatically set to true when you start Strapi for the first time :)
