### ISSUE TITLE
Heroku app deploys but gives application error

### ISSUE THREAD

**Issue by isawrub** [strapi/strapi-legacy-gatsby-blog#11]
I forked just minutes ago and tried to deploy to Heroku.
The app deploys successfully but throws error at startup.

The main error being:
error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
See detailed Heroku error log taken via Heroku CLI below
[isawrub-strapi.txt](https://github.com/strapi/strapi-starter-gatsby-blog/files/4595058/isawrub-strapi.txt)

**Comment by velezhanski** [comment]
Same here

**Comment by joeczar** [comment]
Still broken. It's an issue with the database. It's not getting set up properly.
You can build from scratch using this https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi

**Comment by Mcastres** [comment]
Hello @isawrub, @velezhanski and @joeczar! 

The error appeared on every blog starter but for some reasons I didn't update the Gatsby one, it should be fixed now. What I did is adding the `"ssl": { "rejectUnauthorized": false }` setting inside `backend/config/environment/production/database.json`

I'm very sorry for this!

**Comment by joeczar** [comment]
Hi @Mcastres Thanks so much! Looking forward to playing with this.
