### ISSUE TITLE
Project Broken

### ISSUE THREAD

**Issue by netlander** [strapi/strapi-legacy-gatsby-blog#13]
Following the README to build the project results in the following error, it seems that a `seed` script has gone missing from **backend** `package.json`.
```
 npm run develop:npm

> @ develop:npm /home/xyz/Desktop/development/react/strapi-starter-gatsby-blog
> npm run seed:npm && npm-run-all -p develop:npm:*


> @ seed:npm /home/xyz/Desktop/development/react/strapi-starter-gatsby-blog
> cd backend && npm run seed

npm ERR! missing script: seed
```

**Comment by Mcastres** [comment]
Yes we are not using this seed command anymore, I'll update the README.md

**Comment by vinit-agr** [comment]
Hi @Mcastres , I am facing the same issue. I am following the exact commands mention in the README. Can you please check the README once again. Thanks a lot :)
