### ISSUE TITLE
Deploy to Heroku Not Working

### ISSUE THREAD

**Issue by itwasmattgregg** [strapi/strapi-legacy-gatsby-blog#14]
I clicked the deploy button to heroku and the deploy ran without errors but trying to open the application I get an application error. Logs all say "App crashed". Know what might be causing this?

**Comment by Mcastres** [comment]
What does it say in the logs?

**Comment by itwasmattgregg** [comment]
I was getting a 503 "App crashed" error from a number of endpoints. But about 10 min later it just started working. Not sure what was going on. I didn't change anything to get it to work. Closing.

**Comment by Mcastres** [comment]
Awesome!
