### ISSUE TITLE
image not showing in article

### ISSUE THREAD

**Issue by thezenvan** [strapi/strapi-legacy-gatsby-blog#15]
**Issue**
Image not found when placing in Article

**Steps to reproduce**
- Clone repo, install dependencies, and start Strapi with `yarn develop`
- Open Strapi in browser, [insert image](https://imgur.com/2M3ROCG) into _Article_ (`![blog-header-balloon](/uploads/blog_header_balloon_5db9de92d7.jpeg)`) and save
- start Gatsby with `yarn develop`, open _localhost:8000_ and go to Article which displays a [missing image](https://imgur.com/5gVASUQ)

**Notes**
- Image shows up when going to URL in Strapi `http://0.0.0.0:1337/uploads/blog_header_balloon_5db9de92d7.jpeg` but not in Gatsby `http://localhost:8000/uploads/blog_header_balloon_5db9de92d7.jpeg`

**Specs**
node: v12.16.2
macOS 10.14.4

**Comment by Mcastres** [comment]
Hello @thezenvan,

You can't access to the image with this url `http://localhost:8000/uploads/blog_header_balloon_5db9de92d7.jpeg` since the images are saved in the Strapi project. If you want to access it try `http://localhost:1337/uploads/blog_header_balloon_5db9de92d7.jpeg` :)
