### ISSUE TITLE
npm run setup:npm - missing package.json file after git clone

### ISSUE THREAD

**Issue by PaRoxUs** [strapi/strapi-legacy-gatsby-blog#16]
I get this error when trying to run the setup after cloning the repository.

npm run setup:npm
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /strapi-starter-gatsby-blog/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/strapi-starter-gatsby-blog/package.json'
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by PaRoxUs** [comment]
Sorry, this might just be an issue if you follow the instructions from https://strapi.io/blog/strapi-starter-gatsby-blog

**Comment by Mcastres** [comment]
Yes I changed the way you start your servers :) 
Thanks for noticing @PaRoxUs
