### ISSUE TITLE
allStrapiCategory & allStrapiArticle can't be queried

### ISSUE THREAD

**Issue by hcgaron** [strapi/strapi-legacy-gatsby-blog#3]
I'm not able to get past an area of the tutorial, I'm getting this error:

> There was an error in your GraphQL query:

> Cannot query field "allStrapiCategory" on type "Query".

> If you don't expect "allStrapiCategory" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiCategory" to exist there are a couple of solutions to common problems:

> - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
> - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
> - You want to optionally use your field "allStrapiCategory" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

> It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

I noticed `allStrapiArticle` and `allStrapiCategory` aren't defined anywhere, so I'm not sure how we can query them.  Are they some kinds of defaults?

**Comment by Mcastres** [comment]
Can you tell me what you did in order to reproduce the error?

Is your Strapi server running?

allStrapiArticle and allStrapiCategory are created by Gatsby so it's normal if they are not defined in our code

**Comment by hcgaron** [comment]
Figured it out with some googling of comments in another issue.  It turns out it was an issue with setting the permissions -- must set the User permissions to 'find' and 'find-one'.

**Comment by fodkastir** [comment]
@Mcastres I still get this error when running this starter and I have set both articles and categories for public access. I even set user-permission -> user find and findone to public by following @hcgaron 's comment.
It seems like the plugin is not getting data to graphql layer and it did not throw any error. Is there anything I need to do to make this work?

**Comment by Mcastres** [comment]
Do you have a repository I can check, it's working fine on my side

**Comment by fodkastir** [comment]
@Mcastres I just cloned this repo and followed the instruction for npm.

**Comment by JoeEarly** [comment]
Its fixed on the above merge so you'll have to pull the latest from `master`

**Comment by kylewetton** [comment]
@Mcastres I'm trying to follow the tutorial and have hit this issue. I appreciate that its fixed in this starter repo, but what do we do when we're wanting to follow the steps instead?

I see that the merge simply bumps the gatsby-source-strapi version to 0.0.10, however I'm currently on the latest

` "gatsby-source-strapi": "0.0.12"`
